{
  "status": "error",
  "Data": {
    "status": "error",
    "exceptionType": "com.ibm.bpm.wle.api.UnexpectedFailureException",
    "errorNumber": "CWTBG0019E",
    "errorMessage": "CWTBG0019E: Unexpected exception during execution. Exception information: 'BPDInstance with ID BPDInstance.@instanceId not found.'.",
    "errorMessageParameters": [
      "BPDInstance with ID BPDInstance.@instanceId not found."
    ],
    "programmersDetails": "BPDInstance with ID BPDInstance.@instanceId not found.",
    "responses": null,
    "errorData": null
  }
}